
import { Loader, Sound } from "excalibur";;
import { AsepriteResource } from "@excaliburjs/plugin-aseprite";

const GameIcons = {
  'icons\\arch.dmi': new AsepriteResource('assets/icons/arch.json'),
  'icons\\areas.dmi': new AsepriteResource('assets/icons/areas.json'),
  'icons\\barrel.dmi': new AsepriteResource('assets/icons/barrel.json'),
  'icons\\blue_aura.dmi': new AsepriteResource('assets/icons/blue_aura.json'),
  'icons\\cheese.dmi': new AsepriteResource('assets/icons/cheese.json'),
  'icons\\chest.dmi': new AsepriteResource('assets/icons/chest.json'),
  'icons\\closed_door.dmi': new AsepriteResource('assets/icons/closed_door.json'),
  'icons\\closing_door.dmi': new AsepriteResource('assets/icons/closing_door.json'),
  'icons\\cyan_aura.dmi': new AsepriteResource('assets/icons/cyan_aura.json'),
  'icons\\floor.dmi': new AsepriteResource('assets/icons/floor.json'),
  'icons\\forest.dmi': new AsepriteResource('assets/icons/forest.json'),
  'icons\\grass.dmi': new AsepriteResource('assets/icons/grass.json'),
  'icons\\green_aura.dmi': new AsepriteResource('assets/icons/green_aura.json'),
  'icons\\green_pool.dmi': new AsepriteResource('assets/icons/green_pool.json'),
  'icons\\hearth.dmi': new AsepriteResource('assets/icons/hearth.json'),
  'icons\\hills.dmi': new AsepriteResource('assets/icons/hills.json'),
  'icons\\jug.dmi': new AsepriteResource('assets/icons/jug.json'),
  'icons\\lerf1.dmi': new AsepriteResource('assets/icons/lerf1.json'),
  'icons\\lerf1_death.dmi': new AsepriteResource('assets/icons/lerf1_death.json'),
  'icons\\lerf2.dmi': new AsepriteResource('assets/icons/lerf2.json'),
  'icons\\lerf2_death.dmi': new AsepriteResource('assets/icons/lerf2_death.json'),
  'icons\\magenta_aura.dmi': new AsepriteResource('assets/icons/magenta_aura.json'),
  'icons\\mouth.dmi': new AsepriteResource('assets/icons/mouth.json'),
  'icons\\oasis.dmi': new AsepriteResource('assets/icons/oasis.json'),
  'icons\\ocean.dmi': new AsepriteResource('assets/icons/ocean.json'),
  'icons\\opening_door.dmi': new AsepriteResource('assets/icons/opening_door.json'),
  'icons\\open_door.dmi': new AsepriteResource('assets/icons/open_door.json'),
  'icons\\palm 1 sand.dmi': new AsepriteResource('assets/icons/palm 1 sand.json'),
  'icons\\palm 1.dmi': new AsepriteResource('assets/icons/palm 1.json'),
  'icons\\palm 2 sand.dmi': new AsepriteResource('assets/icons/palm 2 sand.json'),
  'icons\\palm 2.dmi': new AsepriteResource('assets/icons/palm 2.json'),
  'icons\\pc.dmi': new AsepriteResource('assets/icons/pc.json'),
  'icons\\rat.dmi': new AsepriteResource('assets/icons/rat.json'),
  'icons\\rat_corpse.dmi': new AsepriteResource('assets/icons/rat_corpse.json'),
  'icons\\rat_fight.dmi': new AsepriteResource('assets/icons/rat_fight.json'),
  'icons\\red_aura.dmi': new AsepriteResource('assets/icons/red_aura.json'),
  'icons\\red_pool.dmi': new AsepriteResource('assets/icons/red_pool.json'),
  'icons\\scroll.dmi': new AsepriteResource('assets/icons/scroll.json'),
  'icons\\sword.dmi': new AsepriteResource('assets/icons/sword.json'),
  'icons\\table.dmi': new AsepriteResource('assets/icons/table.json'),
  'icons\\thief.dmi': new AsepriteResource('assets/icons/thief.json'),
  'icons\\void.dmi': new AsepriteResource('assets/icons/void.json'),
  'icons\\wall.dmi': new AsepriteResource('assets/icons/wall.json'),
  'icons\\waterfall spray.dmi': new AsepriteResource('assets/icons/waterfall spray.json'),
  'icons\\white_aura.dmi': new AsepriteResource('assets/icons/white_aura.json'),
  'icons\\witch.dmi': new AsepriteResource('assets/icons/witch.json'),
  'icons\\witch_fight.dmi': new AsepriteResource('assets/icons/witch_fight.json'),
  'icons\\yellow_aura.dmi': new AsepriteResource('assets/icons/yellow_aura.json'),
}

const GameIconAnimationsIndex = {
  'icons\\arch.dmi': ['arch_south', 'floor_south'],
  'icons\\areas.dmi': ['entrance_south', 'lights_south', 'mouth_south'],
  'icons\\barrel.dmi': ['_default_south'],
  'icons\\blue_aura.dmi': ['_default_south', 'wall_south'],
  'icons\\cheese.dmi': ['_default_south'],
  'icons\\chest.dmi': ['_default_south'],
  'icons\\closed_door.dmi': ['_default_south'],
  'icons\\closing_door.dmi': ['_default_south'],
  'icons\\cyan_aura.dmi': ['_default_south', 'wall_south'],
  'icons\\floor.dmi': ['_default_south', 'alternate_south', 'wall lower_south', 'wall corner left_south', 'wall corner right_south', 'fountain rim top left_south', 'fountain rim top right_south', 'fountain rim lower left_south', 'fountain rim lower right_south', 'ritual floor 1_south', 'ritual floor 2_south', 'ritual floor 3_south', 'ritual floor 4_south', 'tr-floor 1_south', 'tr-floor 2_south', 'tr-floor 3_south', 'tr-floor 4_south', 'tr-floor 5_south', 'tr-floor wall lower_south'],
  'icons\\forest.dmi': ['_default_south', 'left_south', 'right_south'],
  'icons\\grass.dmi': ['_default_south', 'grass_south', 'flowerz_south'],
  'icons\\green_aura.dmi': ['_default_south', 'wall_south'],
  'icons\\green_pool.dmi': ['fountain center_south', 'top_south'],
  'icons\\hearth.dmi': ['_default_south', '_default_north', '_default_east', '_default_west', 'lit_south', 'lit_north', 'lit_east', 'lit_west'],
  'icons\\hills.dmi': ['_default_south', 'no left_south', 'no right_south', 'no left or right_south'],
  'icons\\jug.dmi': ['red_south', 'green_south', 'blue_south', 'yellow_south', 'purple_south', 'blue-green_south', 'white_south', 'murky_south', 'murky red_south', 'murky blue_south', 'murky purple_south', '_default_south'],
  'icons\\lerf1.dmi': ['_default_south', '_default_north', '_default_east', '_default_west'],
  'icons\\lerf1_death.dmi': ['_default_south', '_default_north', '_default_east', '_default_west'],
  'icons\\lerf2.dmi': ['_default_south', '_default_north', '_default_east', '_default_west'],
  'icons\\lerf2_death.dmi': ['_default_south', '_default_north', '_default_east', '_default_west'],
  'icons\\magenta_aura.dmi': ['_default_south', 'wall_south'],
  'icons\\mouth.dmi': ['_default_south', 'opening door_south', 'open_south', 'not until you feed me_south', 'chewing_south', 'burp_south', 'spit_south'],
  'icons\\oasis.dmi': ['_default_south'],
  'icons\\ocean.dmi': ['_default_south', 'land south 1_south', 'land south 2_south', 'corner_south', 'land west_south', 'temp_south'],
  'icons\\opening_door.dmi': ['_default_south'],
  'icons\\open_door.dmi': ['_default_south'],
  'icons\\palm 1 sand.dmi': ['1_south', '2_south', '3_south', '4_south'],
  'icons\\palm 1.dmi': ['1_south', '2_south', '3_south', '4_south'],
  'icons\\palm 2 sand.dmi': ['_default_south', '1_south', '2_south', '3_south', '4_south'],
  'icons\\palm 2.dmi': ['1_south', '2_south', '3_south', '4_south'],
  'icons\\pc.dmi': ['_default_south', '_default_north', '_default_east', '_default_west', 'with sword_south', 'with sword_north', 'with sword_east', 'with sword_west', 'striking_south', 'striking_north', 'striking_east', 'striking_west'],
  'icons\\rat.dmi': ['_default_south', '_default_north', '_default_east', '_default_west'],
  'icons\\rat_corpse.dmi': ['_default_south'],
  'icons\\rat_fight.dmi': ['_default_south', '_default_north', '_default_east', '_default_west'],
  'icons\\red_aura.dmi': ['_default_south', 'wall_south'],
  'icons\\red_pool.dmi': ['fountain left_south', 'fountain center_south', 'fountain right_south', 'top_south'],
  'icons\\scroll.dmi': ['_default_south'],
  'icons\\sword.dmi': ['_default_south'],
  'icons\\table.dmi': ['upper_south', 'middle_south', '_default_south', 'lower with web_south', 'upper with web_south', 'temp_south'],
  'icons\\thief.dmi': ['_default_south', 'show the sword_south'],
  'icons\\void.dmi': ['_default_south', 'wall left_south', 'wall right_south', 'wall left and right_south', 'wall corner left and right_south', 'wall corner left_south', 'wall corner right_south', 'wall top_south', 'wall inside corner left_south', 'wall inside corner right_south', 'wall inside corner left and right_south', 'left and inside corner right_south', 'right and inside corner left_south', 'tr-wall left_south', 'tr-wall right_south', 'tr-wall lower right_south', 'tr-wall lower_south', 'tr-wall lower left_south', 'wall top and left_south', 'wall top and right_south'],
  'icons\\wall.dmi': ['_default_south', 'alternate_south', 'end right_south', 'end left_south', 'pillar_south', 'fountain left_south', 'fountain right_south', 'wooden wall_south'],
  'icons\\waterfall spray.dmi': ['_default_south'],
  'icons\\white_aura.dmi': ['_default_south', 'wall_south'],
  'icons\\witch.dmi': ['_default_south', 'melting_south'],
  'icons\\witch_fight.dmi': ['_default_south'],
  'icons\\yellow_aura.dmi': ['_default_south', 'wall_south'],
}

const GameSounds = {
  'sounds\\arc.wav': new Sound('assets/sounds/arc.wav'),
  'sounds\\burp.wav': new Sound('assets/sounds/burp.wav'),
  'sounds\\buzz.wav': new Sound('assets/sounds/buzz.wav'),
  'sounds\\door.wav': new Sound('assets/sounds/door.wav'),
  'sounds\\fountain.wav': new Sound('assets/sounds/fountain.wav'),
  'sounds\\ow.wav': new Sound('assets/sounds/ow.wav'),
  'sounds\\puke.wav': new Sound('assets/sounds/puke.wav'),
  'sounds\\castle.mid': new Sound('assets/sounds/castle.wav'),
  'sounds\\lerf.mid': new Sound('assets/sounds/lerf.wav'),
  'sounds\\smooth.mid': new Sound('assets/sounds/smooth.wav'),
  'sounds\\melting.ogg': new Sound('assets/sounds/melting.ogg'),
}


const GameResourceLoader = new Loader()
const allResources: any = { ...GameIcons, ...GameSounds }
for (const res in allResources) {
  GameResourceLoader.addResource(allResources[res])
}

export { GameResourceLoader, GameIcons, GameSounds, GameIconAnimationsIndex }

